# Copyright (C) 2023-present The Project Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from abc import ABC
from dataclasses import dataclass
from cl.runtime.exceptions.error_util import ErrorUtil
from cl.runtime.parsers.locale_key import LocaleKey
from cl.runtime.records.for_dataclasses.extensions import required
from cl.runtime.records.record_mixin import RecordMixin


@dataclass(slots=True, kw_only=True)
class Locale(LocaleKey, RecordMixin[LocaleKey], ABC):
    """Locale in BCP 47 language-country format, for example en-US (second token must be country, not region)."""

    language: str = required()
    """
    Two-letter lowercase language code that LLM is instructed to use, for example 'en' for 'en-US' locale.
    This field is generated by parsing locale_id.
    """

    country: str = required()
    """
    Two-letter UPPERCASE country code that LLM is instructed to use, for example 'US' for 'en-US' locale.
    This field is generated by parsing locale_id.
    """

    def get_key(self) -> LocaleKey:
        return LocaleKey(locale_id=self.locale_id).build()

    def init(self) -> None:
        """Similar to __init__ but can use fields set after construction."""

        # Locale in BCP 47 language-country format, for example en-US (second token must be country, not region)
        locale_tokens = self.locale_id.split("-")
        format_msg = "  - Locale not in BCP 47 ll-CC format where ll is language and CC is country, for example en-US"
        if len(locale_tokens) != 2:
            raise ErrorUtil.value_error(
                self.locale_id,
                details=f"{format_msg}\n  - It has {len(locale_tokens)} dash-delimited tokens instead of 2",
                value_name="locale_id",
                data_type=Locale,
            )
        if not len(language := locale_tokens[0]) == 2 and language.islower():
            raise ErrorUtil.value_error(
                self.locale_id,
                details=f"{format_msg}\n  - Its first part must be a two-letter lowercase language code",
                value_name="locale_id",
                data_type=Locale,
            )
        if not len(country := locale_tokens[1]) == 2 and country.isupper():
            raise ErrorUtil.value_error(
                self.locale_id,
                details=f"{format_msg}\n  - Its second part must be a two-letter UPPERCASE country code (not region)",
                value_name="locale_id",
                data_type=Locale,
            )

        # Assign fields after validation
        self.language = locale_tokens[0]
        self.country = locale_tokens[1]
