# Copyright (C) 2023-present The Project Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import re

class PlotlyUtil:
    """Helper methods for Plotly."""

    @classmethod
    def is_plotly_html(cls, html: str) -> bool:
        """Check if HTML content was generated by Plotly."""
        return "plotly" in html.lower() and ("cdn.plot.ly" in html or "Plotly.newPlot" in html)

    @classmethod
    def sanitize_plotly_html(cls, html: str) -> str:
        """Remove version-dependent content from Plotly HTML for stable test comparison."""
        # Replace versioned CDN URL: plotly-X.X.X.min.js -> plotly.min.js
        html = re.sub(r"plotly-[\d.]+\.min\.js", "plotly.min.js", html)
        # Remove integrity hash (changes with version)
        html = re.sub(r'\s+integrity="[^"]*"', "", html)
        # Remove lowercase GUIDs (e.g., 1d6cd542-2bef-4533-9d0b-40e9723ce8f5)
        html = re.sub(r"[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}", "", html)
        return html
